#
# Copyright (c) 2017 Bitprim developers (see AUTHORS)
#
# This file is part of Bitprim.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

branches:
  only:
  - master
  - dev

env:
   global:
     - PYPI_USER_NAME: "fpelliccioni"

linux: &linux
   os: linux
   sudo: required
   language: python
   python: "3.6"
   services:
     - docker

osx: &osx
   os: osx
   language: generic

# addons:
#   apt:
#     packages:
#       - g++-6
#     sources: &sources
#       - ubuntu-toolchain-r-test


matrix:
   include:
      # - <<: *linux
      #   env: CONAN_GCC_VERSIONS=4.9 CONAN_DOCKER_IMAGE=lasote/conangcc49

      # - <<: *linux
      #   env: CONAN_GCC_VERSIONS=5.4 CONAN_DOCKER_IMAGE=lasote/conangcc54

      # - <<: *linux
      #   env: CONAN_GCC_VERSIONS=6.3 CONAN_DOCKER_IMAGE=lasote/conangcc63

      # - <<: *linux
      #   env: CONAN_CLANG_VERSIONS=3.9 CONAN_DOCKER_IMAGE=lasote/conanclang39

      # - <<: *linux
      #   env: CONAN_CLANG_VERSIONS=4.0 CONAN_DOCKER_IMAGE=lasote/conanclang40

    # GCC 6
      - <<: *linux
        env: C_COMPILER=gcc-6 CXX_COMPILER=g++-6
        compiler: gcc


      # - env: GCC_VERSION=6
      #       os: linux
      #       sudo: required
      #       dist: trusty
      #       group: edge
      #       addons: &gcc6d
      #         apt:
      #           packages:
      #             - g++-6
      #             - libc6
      #           sources:
      #             - ubuntu-toolchain-r-test        

    # - os: linux
    #   env: UNIT_TESTS=true COMPILER=g++-6     BOOST_VERSION=default ENABLE_MEMCHECK=true
    #   compiler: gcc
      
      - <<: *osx
        osx_image: xcode7.3
        env: CONAN_APPLE_CLANG_VERSIONS=7.3

      - <<: *osx
        osx_image: xcode8.2
        env: CONAN_APPLE_CLANG_VERSIONS=8.0

      - <<: *osx
        osx_image: xcode8.3
        env: CONAN_APPLE_CLANG_VERSIONS=8.1

before_install:
  # - if [[ "${C_COMPILER}" != "" ]]; then export CC=${C_COMPILER}; fi
  # - if [[ "${CXX_COMPILER}" != "" ]]; then export CXX=${CXX_COMPILER}; fi

install:
  # - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  # - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-6 /usr/bin/gcc
  # - sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-6 /usr/bin/g++

  ############################################################################
  # All the dependencies are installed in /home/travis/deps/
  ############################################################################
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}

  ############################################################################
  # Install a recent CMake
  ############################################################################
  # - |
  #   if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
  #     CMAKE_URL="https://cmake.org/files/v3.9/cmake-3.9.0-rc5-Linux-x86_64.tar.gz"
  #     mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
  #     export PATH=${DEPS_DIR}/cmake/bin:${PATH}
  #   else
  #     brew upgrade cmake || brew install cmake
  #   fi
  # - cmake --version

  ############################################################################

  - cd ${TRAVIS_BUILD_DIR}
  - chmod +x .travis/install.sh
  - ./.travis/install.sh


script:
  - cd ${TRAVIS_BUILD_DIR}
  - chmod +x .travis/run.sh
  - ./.travis/run.sh

  - cd ${TRAVIS_BUILD_DIR}
  - ls -ltra .travis/
  - chmod a+x .travis/entrypoint.sh
  - ls -ltra .travis/
  - cd bitprim-native
  - /usr/bin/docker run --rm -e PYPI_USER_NAME=${PYPI_USER_NAME} -e PYPI_PASSWORD=${PYPI_PASSWORD} -ti -v ${TRAVIS_BUILD_DIR}/bitprim-native:/home/conan/project -v ${TRAVIS_BUILD_DIR}/.travis/entrypoint.sh:/tmp/entrypoint.sh lasote/conangcc63 /bin/bash -c /tmp/entrypoint.sh

  # - python setup.py sdist
  - twine upload -u ${PYPI_USER_NAME} -p ${PYPI_PASSWORD} dist/*



  # - python ../.travis/docker.py

  # - conan remote add bitprim_temp https://api.bintray.com/conan/bitprim/bitprim
  # - conan install .

  # - pip install  -e .
  # # - gcc -pthread -shared -L/opt/python/3.6.2/lib -Wl,-rpath=/opt/python/3.6.2/lib -L/opt/python/3.6.2/lib -Wl,-rpath=/opt/python/3.6.2/lib build/temp.linux-x86_64-3.6/chain/header.o build/temp.linux-x86_64-3.6/chain/block.o build/temp.linux-x86_64-3.6/chain/merkle_block.o build/temp.linux-x86_64-3.6/bitprimmodule.o build/temp.linux-x86_64-3.6/utils.o build/temp.linux-x86_64-3.6/chain/chain.o build/temp.linux-x86_64-3.6/binary.o build/temp.linux-x86_64-3.6/chain/point.o build/temp.linux-x86_64-3.6/chain/history.o build/temp.linux-x86_64-3.6/chain/word_list.o build/temp.linux-x86_64-3.6/chain/transaction.o build/temp.linux-x86_64-3.6/chain/output.o build/temp.linux-x86_64-3.6/chain/output_list.o build/temp.linux-x86_64-3.6/chain/input.o build/temp.linux-x86_64-3.6/chain/input_list.o build/temp.linux-x86_64-3.6/chain/script.o build/temp.linux-x86_64-3.6/chain/payment_address.o build/temp.linux-x86_64-3.6/chain/compact_block.o build/temp.linux-x86_64-3.6/chain/output_point.o -Lbitprim/lib -L/opt/python/3.6.2/lib -lbitprim-node-cint -lbitprim-node -lpython3.6m -o build/lib.linux-x86_64-3.6/bitprim_native.cpython-36m-x86_64-linux-gnu.so
  # # - travis_wait 30 pip install  -e .
  # - python setup.py bdist_wheel









  # - |
  #   if [[ "${TRAVIS_OS_NAME}" != "linux" ]]; then
  #     twine upload -u ${PYPI_USER_NAME} -p ${PYPI_PASSWORD} dist/*
  #   fi
  
  # - sudo find / -name "site-packages"
  # - ls -ltra /usr/local/lib/python2.7/site-packages
  # - ls -ltra /usr/lib/python3.5/site-packages
  
  # - cd ${TRAVIS_BUILD_DIR}
  # - cd bitprim
  # - pip install  -e .
  # - python setup.py bdist_wheel --universal
  # - twine upload -u ${PYPI_USER_NAME} -p ${PYPI_PASSWORD} dist/*

notifications:
  email: false
  webhooks:
    urls: https://webhooks.gitter.im/e/a19dd2b03bf676d2b622
    on_success: change
    on_failure: always
